[package]
name = "vtest-scan"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
thiserror.workspace = true
vtest-model = { path = "../vtest-model" }
vtest-store = { path = "../vtest-store" }
vtest-adapter-api = { path = "../vtest-adapter-api" }
vtest-adapter-rust = { path = "../vtest-adapter-rust" }
