[package]
name = "vtest-exec"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vtest-adapter-rust = { path = "../vtest-adapter-rust" }
vtest-adapter-api = { path = "../vtest-adapter-api" }
vtest-model = { path = "../vtest-model" }
vtest-store = { path = "../vtest-store" }
